version: '3.1'
services:

  db:
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: hive
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql

  hive:
    build:
      context: .
      dockerfile: Dockerfile-hive
    image: sacheendra/hive:test1
    restart: always
    ports:
      - 9083:9083
    environment:
      SERVICE_OPTS: "-Dorg.jpox.autoCreateSchema=true -Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver -Djavax.jdo.option.ConnectionURL=jdbc:mysql://db:5432/metastore_db?createDatabaseIfNotExist=true -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password"
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SKIP_SCHEMA_INIT: "false"
    volumes:
      - ./warehouse:/opt/hive/data/warehouse
    links:
      - db:db