apiVersion: v1
kind: Pod
metadata:
  name: basic
spec:
  containers:
  - name: basic
    image: sacheendra/contispark:test5
    command: ["/bin/bash", "-c", "sleep 100000"]
    volumeMounts:
      - mountPath: "/opt/contistuff/keyfile"
        name: gcs-key
        readOnly: true
  volumes:
  - name: gcs-key
    secret:
      secretName: gcs-keyfile