apiVersion: v1
kind: Pod
metadata:
  name: executor
spec:
  containers:
  - name: sparkbench
    image: lkmschulz2/sacheens-spark-benchmark:latest
    resources:
      requests:
        ephemeral-storage: "100G"
      limits:
        ephemeral-storage: "120G"
        