apiVersion: v1
kind: Pod
metadata:
  name: executor
  labels:
    spark-app-id: $(SPARK_APP_ID)
spec:
  containers:
  - name: sparkbench
    image: lkmschulz2/sacheens-spark-benchmark:latest
    resources:
      requests:
        ephemeral-storage: "8G"
      limits:
        ephemeral-storage: "8G"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: spark-app-id
            operator: In
            values:
            - $(SPARK_APP_ID)
        topologyKey: "kubernetes.io/hostname"
  imagePullSecrets:
  - name: regcred